[package]
name = "euler"
version = "0.1.0"
authors = ["scullionw <scuw1801@usherbrooke.ca>"]

[dependencies]
time = "0.1"
num-integer = "0.1"

[features]
fp = []

[profile.release]
lto = true
codegen-units = 1