[package]
name = "euler"
version = "0.1.0"
authors = ["scullionw <scuw1801@usherbrooke.ca>"]

[dependencies]
num-integer = "0.1"
fnv = "1.0.6"

[features]
fp = []

[profile.release]
lto = true
codegen-units = 1