[package]
name = "euler"
version = "0.1.0"
authors = ["scullionw <scuw1801@usherbrooke.ca>"]

[dependencies]
time = "*"

[features]
fp = []

[profile.release]
# lto + target cpu native causes program (any bin/p*.rs)
# to never terminate and consume 99% processor
# lto = true 
